import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const acme = Poppins({
  weight: ["400", "100", "500", "700", "900", "300", "600"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${acme.className} antialiased bg-yellow-50 min-h-screen w-full`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
